export type {
  AuditLogEntry,
  ChangePasswordInput,
  CreateStaffUserInput,
  DashboardMetrics,
  ListUsersParams,
  MetricValue,
  PaginatedResult,
  QueryAuditLogParams,
  RoleSummary,
  StaffMember,
  UpdateProfileInput,
} from './admin.types.js';
export type { ApiClientOptions, ApiRequestOptions } from './api-client.js';
export { ApiClient, ApiClientError } from './api-client.js';
export type {
  AssignAttributeInput,
  Attribute,
  AttributeFilterInput,
  AttributeStatus,
  AttributeType,
  AttributeValue,
  AttributeValueInput,
  BulkAssignAttributesInput,
  CreateAttributeInput,
  FacetResult,
  FacetValue,
  ListAttributesParams,
  ProductAttributeAssignment,
  ProductAttributeView,
  ProductSearchSummary,
  SearchProductsParams,
  UpdateAttributeInput,
} from './attribute.types.js';
export type {
  AuthenticatedUser,
  AuthSession,
  LoginInput,
  RegisterInput,
  ResetPasswordInput,
  RoleName,
  SessionSummary,
  UserProfile,
} from './auth.types.js';
export type {
  CreateProductInput,
  ListProductsParams,
  ListPublicProductsParams,
  Product,
  ProductStatus,
  ProductType,
  ProductVisibility,
  UpdateProductInput,
} from './catalog.types.js';
export type {
  AdjustInventoryInput,
  CreateWarehouseInput,
  InventoryItem,
  InventoryListItem,
  InventoryMovement,
  InventoryMovementType,
  ListInventoryParams,
  ListMovementsParams,
  ListWarehousesParams,
  ReservationReferenceInput,
  SetSafetyStockInput,
  UpdateWarehouseInput,
  VariantSummary,
  Warehouse,
  WarehouseStatus,
} from './inventory.types.js';
export type {
  AssetTag,
  CreateFolderInput,
  Folder,
  FolderTreeNode,
  ListMediaParams,
  MediaAsset,
  MediaAssetStatus,
  MediaType,
  UpdateFolderInput,
  UpdateMediaInput,
  UploadMediaInput,
} from './media.types.js';
export type {
  Category,
  CategoryStatus,
  CategoryTreeNode,
  Collection,
  CollectionProductSummary,
  CollectionRule,
  CollectionRuleField,
  CollectionRuleMatchType,
  CollectionRuleOperator,
  CollectionRuleValue,
  CollectionStatus,
  CollectionType,
  CollectionWithProducts,
  CreateCategoryInput,
  CreateCollectionInput,
  ListCollectionsParams,
  ProductPageParams,
  UpdateCategoryInput,
  UpdateCollectionInput,
} from './taxonomy.types.js';
export type {
  BulkUpdateVariantsInput,
  CreateProductOptionInput,
  CreateProductVariantInput,
  GenerateVariantsInput,
  GenerateVariantsResult,
  ListVariantsParams,
  ProductOption,
  ProductOptionValue,
  ProductVariant,
  ProductVariantStatus,
  UpdateProductOptionInput,
  UpdateProductVariantInput,
} from './variant.types.js';
