export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_OPTION_REPOSITORY = Symbol('PRODUCT_OPTION_REPOSITORY');
export const PRODUCT_VARIANT_REPOSITORY = Symbol('PRODUCT_VARIANT_REPOSITORY');

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
