export const WISHLIST_REPOSITORY = Symbol('WISHLIST_REPOSITORY');
export const WISHLIST_ITEM_REPOSITORY = Symbol('WISHLIST_ITEM_REPOSITORY');
export const WISHLIST_PRODUCT_LOOKUP = Symbol('WISHLIST_PRODUCT_LOOKUP');
export const WISHLIST_INVENTORY_AVAILABILITY = Symbol('WISHLIST_INVENTORY_AVAILABILITY');

export const DEFAULT_WISHLIST_NAME = 'Mi lista de deseos';
