export const MEDIA_ASSET_REPOSITORY = Symbol('MEDIA_ASSET_REPOSITORY');
export const FOLDER_REPOSITORY = Symbol('FOLDER_REPOSITORY');
export const ASSET_TAG_REPOSITORY = Symbol('ASSET_TAG_REPOSITORY');
export const MEDIA_ASSET_USAGE_REPOSITORY = Symbol('MEDIA_ASSET_USAGE_REPOSITORY');
export const STORAGE_PORT = Symbol('STORAGE_PORT');

export const DEFAULT_PAGE_SIZE = 24;
export const MAX_PAGE_SIZE = 100;

export const THUMBNAIL_MAX_WIDTH = 400;
export const THUMBNAIL_MAX_HEIGHT = 400;
