export const CART_REPOSITORY = Symbol('CART_REPOSITORY');
export const CART_ITEM_REPOSITORY = Symbol('CART_ITEM_REPOSITORY');
export const COUPON_REPOSITORY = Symbol('COUPON_REPOSITORY');
export const CART_PRODUCT_LOOKUP = Symbol('CART_PRODUCT_LOOKUP');
export const CART_INVENTORY_AVAILABILITY = Symbol('CART_INVENTORY_AVAILABILITY');

export const DEFAULT_CURRENCY = 'MXN';
